CREATE TABLE IF NOT EXISTS person(
    person_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         varchar(100),
    login         varchar(50),
    name          varchar(40),
    birthday      timestamp);

CREATE TABLE IF NOT EXISTS rating(
    rating_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating        varchar(100));

CREATE TABLE IF NOT EXISTS film(
    film_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         varchar(200),
    description   varchar(1000),
    release_data  timestamp,
    duration      integer,
    rating_id     integer REFERENCES rating(rating_id),
    genre_id      integer,
    likes         integer);

CREATE TABLE IF NOT EXISTS genre(
    genre_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre         varchar(100));

CREATE TABLE IF NOT EXISTS film_genre(
    film_id       integer REFERENCES film(film_id),
    genre_id      integer REFERENCES genre(genre_id));

CREATE TABLE IF NOT EXISTS film_like(
    person_id     integer REFERENCES person(person_id),
    film_id       integer REFERENCES film (film_id));

CREATE TABLE IF NOT EXISTS friends(
    person_id     integer REFERENCES person(person_id),
    friends_id    integer REFERENCES person(person_id),
    status_id     boolean);